services:
    user-service:
        build:
            context: ./user_service
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - mongodb
        environment:
            - ENVIRONMENT=development
            - SERVER_PORT=8080
            - MONGODB_URI=mongodb://mongodb:27017
            - MONGODB_DATABASE=user_service
            - JWT_SECRET_KEY=your-development-secret-key-must-be-at-least-32-characters-long
        restart: unless-stopped
        
    mongodb:
        image: mongo:6.0
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        restart: unless-stopped

volumes:
    mongodb_data:
        
            